package hibernate;
// Generated 27-nov-2015 21:33:44 by Hibernate Tools 4.3.1



/**
 * AsigMat generated by hbm2java
 */
public class AsigMat  implements java.io.Serializable {


     private Integer codigo;
     private String dni;
     private String titulo;
     private Integer numCreditos;
     private Integer nota;

    public AsigMat() {
    }

	
    public AsigMat(String dni) {
        this.dni = dni;
    }
    public AsigMat(String dni, String titulo, Integer numCreditos, Integer nota) {
       this.dni = dni;
       this.titulo = titulo;
       this.numCreditos = numCreditos;
       this.nota = nota;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Integer getNumCreditos() {
        return this.numCreditos;
    }
    
    public void setNumCreditos(Integer numCreditos) {
        this.numCreditos = numCreditos;
    }
    public Integer getNota() {
        return this.nota;
    }
    
    public void setNota(Integer nota) {
        this.nota = nota;
    }




}


