package hibernate;
// Generated 27-nov-2015 21:33:44 by Hibernate Tools 4.3.1



/**
 * Asignaturas generated by hbm2java
 */
public class Asignaturas  implements java.io.Serializable {


     private AsignaturasId id;
     private int numCreditos;

    public Asignaturas() {
    }

    public Asignaturas(AsignaturasId id, int numCreditos) {
       this.id = id;
       this.numCreditos = numCreditos;
    }
   
    public AsignaturasId getId() {
        return this.id;
    }
    
    public void setId(AsignaturasId id) {
        this.id = id;
    }
    public int getNumCreditos() {
        return this.numCreditos;
    }
    
    public void setNumCreditos(int numCreditos) {
        this.numCreditos = numCreditos;
    }




}


