package hibernate;
// Generated 27-nov-2015 21:33:44 by Hibernate Tools 4.3.1



/**
 * Aulas generated by hbm2java
 */
public class Aulas  implements java.io.Serializable {


     private AulasId id;

    public Aulas() {
    }

    public Aulas(AulasId id) {
       this.id = id;
    }
   
    public AulasId getId() {
        return this.id;
    }
    
    public void setId(AulasId id) {
        this.id = id;
    }




}


