package pojos;
// Generated 27-nov-2015 21:33:44 by Hibernate Tools 4.3.1



/**
 * AsignaturasId generated by hbm2java
 */
public class AsignaturasId  implements java.io.Serializable {


     private int codigo;
     private String titulo;

    public AsignaturasId() {
    }

    public AsignaturasId(int codigo, String titulo) {
       this.codigo = codigo;
       this.titulo = titulo;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AsignaturasId) ) return false;
		 AsignaturasId castOther = ( AsignaturasId ) other; 
         
		 return (this.getCodigo()==castOther.getCodigo())
 && ( (this.getTitulo()==castOther.getTitulo()) || ( this.getTitulo()!=null && castOther.getTitulo()!=null && this.getTitulo().equals(castOther.getTitulo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodigo();
         result = 37 * result + ( getTitulo() == null ? 0 : this.getTitulo().hashCode() );
         return result;
   }   


}


