package pojos;
// Generated 27-nov-2015 21:33:44 by Hibernate Tools 4.3.1



/**
 * AulasId generated by hbm2java
 */
public class AulasId  implements java.io.Serializable {


     private String nombreEdificio;
     private int numAula;

    public AulasId() {
    }

    public AulasId(String nombreEdificio, int numAula) {
       this.nombreEdificio = nombreEdificio;
       this.numAula = numAula;
    }
   
    public String getNombreEdificio() {
        return this.nombreEdificio;
    }
    
    public void setNombreEdificio(String nombreEdificio) {
        this.nombreEdificio = nombreEdificio;
    }
    public int getNumAula() {
        return this.numAula;
    }
    
    public void setNumAula(int numAula) {
        this.numAula = numAula;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AulasId) ) return false;
		 AulasId castOther = ( AulasId ) other; 
         
		 return ( (this.getNombreEdificio()==castOther.getNombreEdificio()) || ( this.getNombreEdificio()!=null && castOther.getNombreEdificio()!=null && this.getNombreEdificio().equals(castOther.getNombreEdificio()) ) )
 && (this.getNumAula()==castOther.getNumAula());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNombreEdificio() == null ? 0 : this.getNombreEdificio().hashCode() );
         result = 37 * result + this.getNumAula();
         return result;
   }   


}


