package pojos;
// Generated 27-nov-2015 21:33:44 by Hibernate Tools 4.3.1



/**
 * Paa generated by hbm2java
 */
public class Paa  implements java.io.Serializable {


     private Integer codAsignacion;
     private String dni;
     private String apellidos;
     private String nombre;
     private String titulo;
     private String nombreEdificio;
     private Integer numAula;

    public Paa() {
    }

    public Paa(String dni, String apellidos, String nombre, String titulo, String nombreEdificio, Integer numAula) {
       this.dni = dni;
       this.apellidos = apellidos;
       this.nombre = nombre;
       this.titulo = titulo;
       this.nombreEdificio = nombreEdificio;
       this.numAula = numAula;
    }
   
    public Integer getCodAsignacion() {
        return this.codAsignacion;
    }
    
    public void setCodAsignacion(Integer codAsignacion) {
        this.codAsignacion = codAsignacion;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getNombreEdificio() {
        return this.nombreEdificio;
    }
    
    public void setNombreEdificio(String nombreEdificio) {
        this.nombreEdificio = nombreEdificio;
    }
    public Integer getNumAula() {
        return this.numAula;
    }
    
    public void setNumAula(Integer numAula) {
        this.numAula = numAula;
    }




}


